/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rockcarry_ffplayer_player */

#ifndef _Included_com_rockcarry_ffplayer_MediaPlayer
#define _Included_com_rockcarry_ffplayer_MediaPlayer


extern JavaVM *g_jvm;
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM*, void*);
JNIEXPORT JNIEnv* get_jni_env(void);


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rockcarry_ffplayer_MediaPlayer
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;Ljava/lang/Object;IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_rockcarry_ffplayer_MediaPlayer_nativeOpen
  (JNIEnv *, jobject, jstring, jobject, jint, jint, jstring);

/*
 * Class:     com_rockcarry_ffplayer_MediaPlayer
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rockcarry_ffplayer_MediaPlayer_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_rockcarry_ffplayer_MediaPlayer
 * Method:    nativePlay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rockcarry_ffplayer_MediaPlayer_nativePlay
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_rockcarry_ffplayer_MediaPlayer
 * Method:    nativePause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rockcarry_ffplayer_MediaPlayer_nativePause
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_rockcarry_ffplayer_MediaPlayer
 * Method:    nativeSeek
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_rockcarry_ffplayer_MediaPlayer_nativeSeek
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_rockcarry_ffplayer_MediaPlayer
 * Method:    nativeSetParam
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_com_rockcarry_ffplayer_MediaPlayer_nativeSetParam
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     com_rockcarry_ffplayer_MediaPlayer
 * Method:    nativeGetParam
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_rockcarry_ffplayer_MediaPlayer_nativeGetParam
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_rockcarry_ffplayer_MediaPlayer
 * Method:    nativeSetDisplaySurface
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rockcarry_ffplayer_MediaPlayer_nativeSetDisplaySurface
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_rockcarry_ffplayer_MediaPlayer
 * Method:    nativeSetDisplayTexture
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rockcarry_ffplayer_MediaPlayer_nativeSetDisplayTexture
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
