/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rockcarry_ffplayer_player */

#ifndef _Included_com_rockcarry_ffplayer_player
#define _Included_com_rockcarry_ffplayer_player
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rockcarry_ffplayer_player_RENDER_LETTERBOX
#define com_rockcarry_ffplayer_player_RENDER_LETTERBOX 0L
#undef com_rockcarry_ffplayer_player_RENDER_STRETCHED
#define com_rockcarry_ffplayer_player_RENDER_STRETCHED 1L
#undef com_rockcarry_ffplayer_player_PARAM_VIDEO_WIDTH
#define com_rockcarry_ffplayer_player_PARAM_VIDEO_WIDTH 0L
#undef com_rockcarry_ffplayer_player_PARAM_VIDEO_HEIGHT
#define com_rockcarry_ffplayer_player_PARAM_VIDEO_HEIGHT 1L
#undef com_rockcarry_ffplayer_player_PARAM_VIDEO_DURATION
#define com_rockcarry_ffplayer_player_PARAM_VIDEO_DURATION 2L
#undef com_rockcarry_ffplayer_player_PARAM_VIDEO_POSITION
#define com_rockcarry_ffplayer_player_PARAM_VIDEO_POSITION 3L
#undef com_rockcarry_ffplayer_player_PARAM_RENDER_MODE
#define com_rockcarry_ffplayer_player_PARAM_RENDER_MODE 4L
/*
 * Class:     com_rockcarry_ffplayer_player
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_rockcarry_ffplayer_player_open
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_rockcarry_ffplayer_player
 * Method:    close
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rockcarry_ffplayer_player_close
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rockcarry_ffplayer_player
 * Method:    play
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rockcarry_ffplayer_player_play
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rockcarry_ffplayer_player
 * Method:    pause
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rockcarry_ffplayer_player_pause
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rockcarry_ffplayer_player
 * Method:    seek
 * Signature: (Ljava/lang/Object;J)V
 */
JNIEXPORT void JNICALL Java_com_rockcarry_ffplayer_player_seek
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_rockcarry_ffplayer_player
 * Method:    setparam
 * Signature: (Ljava/lang/Object;II)V
 */
JNIEXPORT void JNICALL Java_com_rockcarry_ffplayer_player_setparam
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_rockcarry_ffplayer_player
 * Method:    getparam
 * Signature: (Ljava/lang/Object;I)I
 */
JNIEXPORT jint JNICALL Java_com_rockcarry_ffplayer_player_getparam
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
